spring.application.name=BookExchangeApp
spring.data.mongodb.uri=mongodb+srv://2023tm93617:TAJ5DbJgYqXYdf0F@mymongocluster.2eoct.mongodb.net/?retryWrites=true&w=majority&appName=myMongoCluster
spring.data.mongodb.database=BookExchangeDB